# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Build
  displayName: Build stage
  pool:
    name: Default
    demands:
        - dotnet
  variables:
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
  jobs:
    - job: Build_Solution
      displayName: Whole solution build process
      steps:
      - task: UseDotNet@2
        displayName: 'Use .NET 6.0.402 sdk'
        inputs:
          packageType: sdk
          version: 6.0.402

      - task: DotNetCoreCLI@2
        displayName: 'Build solution ShoppingApp.sln'
        inputs:
          command: build
          projects: 'ShoppingApp.sln'
          configuration: '$(buildConfiguration)'

      # Run Tests
      - task: DotNetCoreCLI@2
        displayName: 'Run Integration Tests'
        inputs:
          command: test
          projects: |
            test/ShoppingApp.Tests
            publishTestResults: true